### ISSUE TITLE
XBMC crashes when playing a movie

### ISSUE THREAD

**Issue by Jaymzu** [bogde/xbmc.serialepenet.ro#5]
Select seriale pe net, go to a movie, click "dati click aici pentru vizionare" -> xbmc crashes. 

Running XBMC nightly build on OSX Mavericks. 

Sadly the lower quality 990.ro works flawlessly ;(

**Comment by bogde** [comment]
i didn't test on mac os. can you provide the xbmc.log. on the raspberry pi is located in /home/pi/.xbmc/temp/xbmc.log, i dont know where it's stored on the mac.

can you let me know what movie you were trying to watch when it crashed.

**Comment by Jaymzu** [comment]
For further references, the log file on OSX is in /Users/USERNAME/Library/Logs
I don't know how to attach the log file it here so here's a link to it : http://cl.ly/2D1y2R1S043I . 
Reg what I was watching, it's the same behaviour no matter what I tried. The url is included in the log file anyway. 

Let me know if there's anything more I can do to help

**Comment by bogde** [comment]
I got the log, please delete it from that server. thanks

**Comment by Jaymzu** [comment]
Done. Looking forward to any updates.

**Comment by bogde** [comment]
i strongly believe this is a bug in the xbmc implementation as it only seems to affect macos. i tested the windows nightly build and it works fine.

to document the problem: the macos nightly build of xbmc crashes on xbmc.Player().play(url) (even if url points to a local file).

990.ro works because it doesn't use the above function. it doesn't have to, because subtitles are apparently embedded in the video so no further processing is needed. i assume other plugins that use xbmc.Player() also fail to work with this version.

anyway, i do have some good news. i created a workaround for this problem. it should work fairly well for now. you can find it in the macos branch. let me know if you need a zip file and i'll create it for you, if you don't want to use git.

thanks for your feedback.

**Comment by Jaymzu** [comment]
No more crashes. Thanks, mate;)

Bafta !

**Comment by bogde** [comment]
no problem :)
